
service: multifunctions

package:
  individually: true

provider:
  name: aws
  runtime: python3.6

functions:
  function1:
    handler: handler.function1
  function2:
    handler: handler1.function2
